name: Deploy Streamlit App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: streamlit/streamlit-action@main
        with:
          app: app.py
          cloud: true