name: Deploy to Streamlit Cloud
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir
          pip list  # Para debug nos logs
      - name: Deploy to Streamlit
        uses: streamlit/streamlit-action@main
        with:
          app: app.py
          cloud: true
          secrets: |
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
