name: Deploy Streamlit App
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt
      - uses: streamlit/streamlit-action@main
        with:
          app: app.py  # Confira se este é o nome do seu arquivo principal
          cloud: true
