name: Deploy Streamlit App
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install notion-client openai
      - uses: streamlit/streamlit-action@main
        with:
          app: app.py
          cloud: true
          secrets: |
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
