[server]
headless = true
port = 8080
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 50  # Tamanho máximo em MB para uploads

[browser]
serverAddress = "0.0.0.0"
gatherUsageStats = false  # Desativa telemetria
