[server]
headless = true
port = 8080
enableCORS = false
enableXsrfProtection = true
maxMessageSize = 50

[client]
caching = false
showErrorDetails = false  # Reduz vazamento de informações

[browser]
serverAddress = "0.0.0.0"
serverPort = 8080

